baseURL = '/'
relativeURLs = true
languageCode = 'en-us'
title = 'Fidelity Connect | Recruitment Agency Kenya'
[related]
  threshold = 1
  toLower = true
  includeNewer = true

[[related.indices]]
  name = "categories"
  weight = 100

[taxonomies]
    category = "categories"
    platform = "platform"

[menu]

  [[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 10

  [[menu.main]]
    name = "Our Services"
    url = "/services/"
    weight = 20

  [[menu.main]]
    name = "Our Team"
    url = "/team/"
    weight = 30

  [[menu.main]]
    name = "Blog"
    url = "/blogs/"
    weight = 40

  [[menu.main]]
    name = "Events"
    url = "/events"
    weight = 50


 

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "Fidelity Connect places Kenyan talent in verified jobs across Saudi Arabia, Qatar, Kuwait, UAE and the UK. Apply for vetted Gulf job openings today."
  images = ["/images/hero.png"]
